### ISSUE TITLE
/lib/lcd/lcd.py: IndexError: index out of range

### ISSUE THREAD

**Issue by idk-br9** [dhalbert/CircuitPython_LCD#10]
i have circuitpython 9 and yd-rp2040, there is a full text of error:
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "/lib/lcd/lcd.py", line 199, in print
  File "/lib/lcd/lcd.py", line 288, in write
  File "/lib/lcd/lcd.py", line 181, in set_cursor_pos
IndexError: index out of range

**Comment by mirkokral** [comment]
What's your code or a subset of it near the crash (line 13)?
